server:
  port: 8888
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/result
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800
spring:
   resources:
     cache:
       period: -1
   profiles.active: dev

#  kafka配置
   kafka:
     consumer:
        bootstrap-servers: 10.0.11.30:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        group-id: methane-ga
        enable-auto-commit: true
        auto-commit-interval: 1s
        auto-offset-reset: latest
        heartbeat-interval: 15s
        max-partition-fetch-bytes: 3027200
        session-timeout: 30s
        request-timeout: 90s
        max-blocking-num: 10000
        topic: methane-si-ga
     producer:
        bootstrap-servers: 10.0.11.30:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        acks: 0
        batch-size: 16384
        compression-type: gzip
        buffer-memory: 33554432
        retries: 0


